services:
  - type: web
    name: sanich-farms-web
    env: node # or python, ruby, go, elixir, rust, etc.
    buildCommand: npm install && npm build # Or pip install -r requirements.txt, bundle install, etc.
    startCommand: npm start # Or gunicorn myapp.wsgi, rails s, etc.
    plan: starter # Or professional, etc.
    autoDeploy: true # Automatically deploy on new commits to the linked branch
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables as needed
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: my-database # Name of a Render Postgres database
      #     property: connectionString
      # - key: SECRET_KEY_BASE
      #   generateValue: true # Render will generate a strong secret
