# render.yaml
services:
  - type: web
    name: sanich-farms-backend
    env: node
    # Crucially, tell Render where to find the service's root directory relative to the Git repo root
    rootDir: ./backend/
    buildCommand: yarn install # This command will now run inside the 'backend' directory
    startCommand: yarn start   # This command will also run inside the 'backend' directory
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Add other backend-specific environment variables here
      # - key: DB_HOST
      #   value: your_db_host
      # - key: DB_USER
      #   value: your_db_user
